apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: y7h2k5yd1-go 
  janus-idp.io/tekton: y7h2k5yd1-go
  backstage.io/kubernetes-id: y7h2k5yd1-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: y7h2k5yd1-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml