apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: y7h2k5yd1-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: y7h2k5yd1-go 
  name: y7h2k5yd1-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: y7h2k5yd1-go 
